import '../../styles/scss/_app.scss';
import React from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import DashboardLayout from 'components/Layouts';
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from '_context/authContext';
import Head from 'next/head';

const layouts = {
  DashboardLayout: DashboardLayout,
  NoLayout: '',
};

function MyApp({ Component, pageProps }) {
  const Layout = layouts[Component.layout] || ((pageProps) => <Component>{pageProps}</Component>);
  return (
    <>
      <Head>
        <title>NiftyTrader Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>
      <ToastContainer />
      <AuthProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </AuthProvider>
    </>
  );
}

export default MyApp;
