import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>NiftyTrader Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="icon" href="/logo-icon.png" />
      </Head>
    </>
  );
}
